# /// script
# requires-python = ">=3.12"
# dependencies = [
#     "pyyaml>=6.0",
# ]
# ///
# SPDX-License-Identifier: AGPL-3.0-or-later
# SPDX-FileCopyrightText: 2026 The hypotheses subnet contributors

"""Generate `docs/spec/load-for-index.md` from spec front-matter.

Spec docs declare which task tags they belong to via the
`load_for:` front-matter field. The AGENTS.md context-routing
table assembles per-task minimum load-sets from these tags. This
script produces the *reverse* index: for each tag, list every
spec doc that declares it, with the doc's declared `tokens:`,
and a per-tag total.

The output is derived data — the canonical home for `load_for`
remains the per-doc front-matter. Every regeneration must produce
byte-identical output for the same inputs (sorted, deterministic).

Run:
    uv run scripts/gen_load_for_index.py

Used by `.github/workflows/load-for-index.yml`.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _doc_lib import parse_frontmatter  # noqa: E402

OUT_PATH = Path("docs/spec/load-for-index.md")
SCAN_GLOBS: tuple[str, ...] = (
    "docs/spec/*.md",
    "docs/spec/formal/*.md",
)
EXCLUDE_DIR_PARTS: frozenset[str] = frozenset({"antipatterns", "_schemas"})

HEADER = (
    "---\n"
    "name: load-for index\n"
    "description: reverse index of `load_for:` tags to spec docs and token totals\n"
    "tokens: 1100\n"
    "load_for: [agent-operator, governance, implementation, proposal, review]\n"
    "depends_on: []\n"
    "kind: reference\n"
    "---\n\n"
    "# Load-for index\n\n"
    "<!-- generated:by=scripts/gen_load_for_index.py "
    "from=docs/spec/*.md front-matter `load_for:`; "
    "do not edit by hand. See docs/CONTRIBUTING-DOCS.md. -->\n\n"
    "Reverse index of the `load_for:` front-matter tag across the spec\n"
    "tree. Generated by `scripts/gen_load_for_index.py`.\n\n"
    "For each task tag, lists every spec doc that declares it, with the\n"
    "doc's declared `tokens:` and a per-tag total. The canonical source\n"
    "is each doc's front-matter; this file restates by reference only.\n"
    "AGENTS.md `## Context routing` selects subsets of these per-task\n"
    "load-sets — see that table for per-task curated bundles.\n"
)


def main() -> int:
    by_tag: dict[str, list[tuple[str, Path, int]]] = {}
    for glob in SCAN_GLOBS:
        for path in sorted(Path().glob(glob)):
            if any(part in EXCLUDE_DIR_PARTS for part in path.parts):
                continue
            data, _, _ = parse_frontmatter(path)
            if not data:
                continue
            tags = data.get("load_for", []) or []
            tokens = data.get("tokens", 0) or 0
            name = data.get("name", path.stem)
            for tag in tags:
                by_tag.setdefault(tag, []).append((name, path, tokens))

    out: list[str] = [HEADER]
    for tag in sorted(by_tag):
        entries = sorted(by_tag[tag], key=lambda e: e[1])
        total = sum(t for _, _, t in entries)
        out.append(f"\n## `{tag}`\n\n")
        out.append(f"Total declared tokens: **{total}**.\n\n")
        out.append("| doc | name | tokens |\n")
        out.append("|-----|------|--------|\n")
        for name, path, tokens in entries:
            out.append(
                f"| [{path}]({path.relative_to('docs/spec')}) | {name} | {tokens} |\n"
            )

    OUT_PATH.write_text("".join(out))
    print(f"wrote {OUT_PATH} ({OUT_PATH.stat().st_size} bytes; {len(by_tag)} tags)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
